---
- name: Visual Studio Code
  homebrew_cask: name="visual-studio-code" state="present"

- name: vscode command line (code)
  file: 
    src: /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
    dest: /usr/local/bin/code
    state: link

# TODO - setting up python path