# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create localbox
  config.vm.define :localbox do |config|
      config.vm.box = "ubuntu/xenial64"
      config.vm.hostname = "localbox"
      config.vm.network :private_network, ip: "10.0.15.100"
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
      config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
      config.ssh.insert_key = false

      config.vm.provision "file", source: "~/.dev/ca/root/certs/root.cert.pem", destination: "~/root.cert.pem"

      config.vm.provision :shell, path: "box-setup.sh"
  end

end
